### ISSUE TITLE
Migrate to platform.io

### ISSUE THREAD

**Issue by valerio-vaccaro** [btcven/locha-mesh-app#6]
In order to have a more modern interface/building system and in order to avoid compilation problems (expecially on various esp32 platforms with minimal changes e.g. heltech, ttgo, lopy ...) I suggest migrate from arduino to platform.io. 
You can still use all arduino library as well.

**Comment by luisan00** [comment]
It is true, it is a modern and pleasant interface, but it has its own idf and was discarded when we decided on the standards and the rude Arduino is still a standard these days. For example, Marlin continues to use Arduino as a reference. But the compilation process is independent of the development process. The locha binaries are created automatically every day through CI depending on the definitions of the board that you will find in the hardware folder, You can use VSCode, Sublime text,  Atom, Eclipse, Atmel Studio and a long etc for coding, debugging and compilation. Try to define your board and test it.
